# basic options
title: Your awesome title
author: Sam Christian 
email: SamChristian.2727@gmail.com
description: A wonderful site
github_username:  Sam-2727

# Build settings
markdown: kramdown
theme: minima
